### ISSUE TITLE
Error: No input found for daterange

### ISSUE THREAD

**Issue by odigity** [jordanbrock/bootstrap-daterangepicker-rails#24]
Using Rails 4.2.0 with PostgreSQL 9.3.5.  Have a table with a column called `period`, type `daterange`.  I did the following:

1. Installed your gem (add to Gemfile, bundle, restart web server).
2. Added appropriate CSS and JS files (checked source to ensure they were getting included).
3. Added the three line script tag contents to my template.
4. Added a call to f.input for my column using simple_form (3.1.0), exactly as in the README.

Not sure what I'm doing wrong.

**Comment by odigity** [comment]
Hope we can resolve this, your demo looked amazing.

**Comment by jordanbrock** [comment]
Hi,

I've never tested this with PostgreSQL. It seems to me that this is more likely a simple_form issue, rather than related to the javascript, as the error is being raised on the :daterange field type.

If you can get it working with a PostgreSQL backend can you let me know? 

Cheers,
Jordan
