### ISSUE TITLE
Release new gem version on rubygems.org?

### ISSUE THREAD

**Issue by frenkel** [jordanbrock/bootstrap-daterangepicker-rails#37]
Thanks for this gem! Now that Rails 5 is out, could you release a new version based on current master? I see you fixed it's compatibility there.

**Comment by francocatena** [comment]
+1

**Comment by Apokly** [comment]
Any news ?

**Comment by jordanbrock** [comment]
Sorry for the delay. Done:

https://rubygems.org/gems/bootstrap-daterangepicker-rails/versions/0.1.5

**Comment by frenkel** [comment]
Great, thanks!
