### ISSUE TITLE
Upgrading gem

### ISSUE THREAD

**Issue by JiProchazka** [jordanbrock/bootstrap-daterangepicker-rails#42]
Hi, pls can you upgrade the gem? There is the same version of `0.1.5`, but in the gemspec there is an old runtime dependency of railties `railties < 5.1, >= 4.0`.
Should be `railties < 5.2, >= 4.0` as it is already in repo.

Thanks

**Comment by jordanbrock** [comment]
Just pushed 0.1.7. Sorry for the mix-up

**Comment by JiProchazka** [comment]
Thanks!
