### ISSUE TITLE
ActionView::Template::Error (couldn't find file 'bootstrap' with type 'text/css'

### ISSUE THREAD

**Issue by AdminDev826** [jordanbrock/bootstrap-daterangepicker-rails#46]
# application.css

/*
 *= require_self
*= require style
*= require simple_calendar
*= require bootstrap
 *= require daterangepicker
 */

**Comment by LeoSatch** [comment]
I am migrating from Rails 4 to 5 and I have this error : ActionView::Template::Error (couldn't find file 'bootstrap' with type 'text/css'

Can't find a way to get rid of it.

I only find people with the same issue but no solution.

Please help ;-)
